Models creation
patostickar/carry pull request #1
Opened 2022-05-23 19:40 UTC by zayrarepositor

customer model creation.

there are two comments to review:

- state_name (is it necessary?)

- isAdmin was added

- isPremium, isBanned were modified name

2022-05-23 19:49 UTC, patostickar reviewed
Me parece el apellido debería ser required.
Codigo postal y ciudad, no sé, es lo común.

2022-05-23 19:49 UTC, patostickar commented on api/src/models/Customer.js
> +        type: DataTypes.STRING,
required: true

2022-05-23 19:49 UTC, patostickar commented on api/src/models/Customer.js
>        is necessary??*/
supongo que da igual, es lo común

2022-05-23 20:09 UTC, zayrarepositor commented
customer model update

last_name is required

2022-05-23 22:49 UTC, zayrarepositor reviewed
new models for review @patostickar

2022-05-24 02:56 UTC, Dakkai approved these changes

2022-05-24 03:11 UTC, patostickar requested changes

2022-05-24 03:11 UTC, patostickar commented on api/src/models/Booking.js
> +      pickup_location: {
remove pickup and dropoff location

2022-05-24 03:11 UTC, patostickar commented on api/src/models/Car.js
> +      },
lo mismo, sólo queda id, el resto son todas foreign keys

2022-05-24 03:11 UTC, patostickar commented
Después de hacer los cambios, tengo que marcar la conversación como resulta (la próxima no lo hago sino tengo que marcar yo explícitamente) y después podemos hacer el merge

2022-05-24 04:01 UTC, patostickar approved these changes

2022-05-24 04:01 UTC, merged